# Conclusion

```{r}
rm(list = ls())
```

This project used data science and machine learning techniques to predict Swiss real estate prices, focusing on data scrapped from ImmoScout24. Through data analysis and model evaluation, several insights and conclusions were drawn:

## Results
### Linear Regression Model:
- Initially employed, the linear regression model provided moderate explanatory power with an R-squared of 0.493 and an RMSE of 980'302.
- Attempts to refine the model through stepwise regression slightly enhanced its performance. However, challenges persisted with higher price points and multicollinearity.
- Simplifying the model by focusing on specific cantons and removing less significant variables improved stability and predictive power, though challenges remained with higher property prices. Furthermore, problems with test data metrics being higher than training data metrics were observed, indicating peculiarities in generalization across different data subsets.


### Random Forest Model:
- The Random Forest model addressed the limitations of linear regression by capturing non-linear relationships, achieving higher accuracy.
- Performance metrics (higher R-squared and lower RMSE and MAE) indicated better predictive accuracy compared to linear regression but tend to overfit if we are not careful with the data taken
- After varied tests, reducing the model complexity by focusing on specific cantons and year categories improved the performance and reduced overfitting
- The hyperparameter-tuned model stands out as the superior option, primarily due to the strategic adjustment of the number of variables considered for splitting at each leaf node (mtry), which significantly enhances the model's generalization capabilities from training to unseen test data, thereby optimizing performance metrics like RMSE, MAE, and R-squared.
- Variable importance analysis highlighted square_meters as the most influential predictor, validating its significant impact on property prices.

### Model Optimization:
- Both linear regression and Random Forest models were refined through hyperparameter tuning and cross-validation, ensuring robust predictions.
- Focused analysis on specific cantons and filtering data to a realistic price range further enhanced model performance and reduced overfitting.

## Recommendation and Discussion

- **Observations : ** For accurate property price predictions, a model tailored to specific cantons, year-categories, and price ranges is more effective. Constraints prevented us from detailing all 26 cantons and combined with all 11 year category, as it would prove to be too computationally heavy.
- **Business Implications : **Tailored models are recommended to accurately predict property prices, offering crucial insights for real estate investors and policymakers.
- **Limitations and Future Directions:** While effective, the models require continuous refinement and expansion of the dataset to include a wider range of variables. Further research could explore the integration of economic indicators, a time-series analyiss, and extend the analysis to other regions or sectors. Future research could explore incorporating additional variables, other models, and employing newer analytical methods, such as Deep Learning Techniques or Geospatial Analysis, to enhance the models accuracy and applicability.

## Final Thoughts

We specified in the intro that interest rates or any other time economic indicator influence housing price. This is indeed true. However, our project specifically focuses on a snapshot of the current market, without employing time series analysis. This means that while such factors are crucial in a broader economic context, they do not directly influence the outcomes of our study. Indeed, our analysis is rooted in the conditions and data of a specific moment when our data was scraped, making temporal variables like interest rate outside the scope of our predictive modeling. Consequently, the implications of our findings are best applied to immediate decision-making rather than long-term forecasting.

Ultimately, the broad potential of machine learning in real estate valuation offers significant opportunities for insightful decision-making in this sector.
